### ISSUE TITLE
Implement workflowState Start API

### ISSUE THREAD

**Issue by longquanzheng** [cadence-oss/iwf-java-sdk#1]
implement https://github.com/cadence-oss/iwf-java/blob/main/core/src/main/java/iwf/core/spring/controller/ApiController.java#L23 

AC & steps (separate PRs):
1. Copy the SDK code from prototype 
1. Copy a demo workflow as user code in test folder, and let it run with the SDK (with the spring controller)
2. Provide a workflowRegistry with register APIs to register workflow type(use workflow class short name)
3. On invoking workflowState.Start, find the workflow from workflowRegistry, and invoke the start API from user code, collect the command requests and return back to caller

**Comment by longquanzheng** [comment]
1 step : https://github.com/cadence-oss/iwf-java/pull/2

**Comment by duoertai** [comment]
step2: https://github.com/cadence-oss/iwf-java/pull/5
